resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: webfrontend-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - ConnectionStrings__cache=cache:6379,password=6AxNDvcyaAxBcMcTGjS7TC
    - CACHE_HOST=cache
    - CACHE_PORT=6379
    - CACHE_PASSWORD=6AxNDvcyaAxBcMcTGjS7TC
    - CACHE_URI=redis://:{cache-password-uri-encoded.value}@cache:6379
    - APISERVICE_HTTP=http://apiservice:8080
    - services__apiservice__http__0=http://apiservice:8080
    - ASPNETCORE_URLS=http://+:8080;

